name: This describes workflows and events
run-name: event-types
on:
  workflow_run:
        workflows: ['Full Production Deploy']
        types :
            - completed 
  pull_request:
    types: [created]
    branches: [main]
  push:
    branches-ignore: [main]
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
    inputs:
      first_word:
          description: give first word to start
          type: string
jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
     - name: call-reusable
       uses: ./.github/workflows/first-workflow.yaml
       with: 
         first: reusable
         second: caller

  


