name: DevOps Workflow
 
on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
 
  workflow_dispatch:
 
permissions:
  contents: write         # For pushing code or building packages
  pull-requests: write    # For merging PRs
  issues: write           # For creating issues
  packages: write         # For publishing packages
 
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/test-image:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/test-image:latest
 
  create-issue-uses:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Automated Issue"
          content-filepath: .github/ISSUE_TEMPLATE.md
  create-issue-cli:
     runs-on: ubuntu-latest
     steps:
       - name: Authenticate GH CLI
         run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token
 
       - name: Create an Issue
         run: |
          gh issue create \
            --title " Automated Issue from GitHub Actions" \
            --body "This issue was auto-generated by a workflow run." \
            --label "bug"
 
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'automerge'
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
