name: first-workflow
on:
  workflow_call:
    inputs:
      first:
        required: true
        type: string
      second:
          required : true
          type : string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "building ${{inputs.first}}and${{inputs.second} job"
   

