name: first-workflow
on:
  workflow_call:
    secrets: 
      Token:
        description: 'Give API_TOKEN'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.API_TOKEN }}
      - name: echo message
        run: echo "This workflow is called workflow calling is caller workflow"

