name: Reuseable-workflow
 
on:
  workflow_call:
    secrets: 
      Token:
        description: 'Authentication_token'
 
jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.TOKEN }}
      - name: echo message
        run: echo "This workflow is calling another workflow"
